//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skyticket.ContactService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.tickets.com/", ConfigurationName="ContactService.ws_ValidaDatos_Clie")]
    public interface ws_ValidaDatos_Clie {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tickets.com/ws_ValidaDatos_Clie/ConsultaRequest", ReplyAction="http://ws.tickets.com/ws_ValidaDatos_Clie/ConsultaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Skyticket.ContactService.ConsultaResponse Consulta(Skyticket.ContactService.ConsultaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tickets.com/ws_ValidaDatos_Clie/ConsultaRequest", ReplyAction="http://ws.tickets.com/ws_ValidaDatos_Clie/ConsultaResponse")]
        System.Threading.Tasks.Task<Skyticket.ContactService.ConsultaResponse> ConsultaAsync(Skyticket.ContactService.ConsultaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tickets.com/ws_ValidaDatos_Clie/ActualizaRequest", ReplyAction="http://ws.tickets.com/ws_ValidaDatos_Clie/ActualizaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Skyticket.ContactService.ActualizaResponse Actualiza(Skyticket.ContactService.ActualizaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tickets.com/ws_ValidaDatos_Clie/ActualizaRequest", ReplyAction="http://ws.tickets.com/ws_ValidaDatos_Clie/ActualizaResponse")]
        System.Threading.Tasks.Task<Skyticket.ContactService.ActualizaResponse> ActualizaAsync(Skyticket.ContactService.ActualizaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tickets.com/ws_ValidaDatos_Clie/InsertaRegRequest", ReplyAction="http://ws.tickets.com/ws_ValidaDatos_Clie/InsertaRegResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Skyticket.ContactService.InsertaRegResponse InsertaReg(Skyticket.ContactService.InsertaRegRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tickets.com/ws_ValidaDatos_Clie/InsertaRegRequest", ReplyAction="http://ws.tickets.com/ws_ValidaDatos_Clie/InsertaRegResponse")]
        System.Threading.Tasks.Task<Skyticket.ContactService.InsertaRegResponse> InsertaRegAsync(Skyticket.ContactService.InsertaRegRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.tickets.com/")]
    public partial class ticketsValidaBeans : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string id_clienteField;
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string id_cliente {
            get {
                return this.id_clienteField;
            }
            set {
                this.id_clienteField = value;
                this.RaisePropertyChanged("id_cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.tickets.com/")]
    public partial class contactInBeans : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string datoField;
        
        private string descriptionField;
        
        private string first_nameField;
        
        private int id_clienteField;
        
        private bool id_clienteFieldSpecified;
        
        private string last_nameField;
        
        private string primary_address_cityField;
        
        private string primary_address_countryField;
        
        private string primary_address_postalcodeField;
        
        private string primary_address_stateField;
        
        private string primary_address_streetField;
        
        private string rfcField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string dato {
            get {
                return this.datoField;
            }
            set {
                this.datoField = value;
                this.RaisePropertyChanged("dato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string first_name {
            get {
                return this.first_nameField;
            }
            set {
                this.first_nameField = value;
                this.RaisePropertyChanged("first_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id_cliente {
            get {
                return this.id_clienteField;
            }
            set {
                this.id_clienteField = value;
                this.RaisePropertyChanged("id_cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_clienteSpecified {
            get {
                return this.id_clienteFieldSpecified;
            }
            set {
                this.id_clienteFieldSpecified = value;
                this.RaisePropertyChanged("id_clienteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                this.last_nameField = value;
                this.RaisePropertyChanged("last_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string primary_address_city {
            get {
                return this.primary_address_cityField;
            }
            set {
                this.primary_address_cityField = value;
                this.RaisePropertyChanged("primary_address_city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string primary_address_country {
            get {
                return this.primary_address_countryField;
            }
            set {
                this.primary_address_countryField = value;
                this.RaisePropertyChanged("primary_address_country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string primary_address_postalcode {
            get {
                return this.primary_address_postalcodeField;
            }
            set {
                this.primary_address_postalcodeField = value;
                this.RaisePropertyChanged("primary_address_postalcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string primary_address_state {
            get {
                return this.primary_address_stateField;
            }
            set {
                this.primary_address_stateField = value;
                this.RaisePropertyChanged("primary_address_state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string primary_address_street {
            get {
                return this.primary_address_streetField;
            }
            set {
                this.primary_address_streetField = value;
                this.RaisePropertyChanged("primary_address_street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string rfc {
            get {
                return this.rfcField;
            }
            set {
                this.rfcField = value;
                this.RaisePropertyChanged("rfc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.tickets.com/")]
    public partial class contactsUpBeans : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string datoField;
        
        private string descriptionField;
        
        private string first_nameField;
        
        private int id_clienteField;
        
        private bool id_clienteFieldSpecified;
        
        private string last_nameField;
        
        private string primary_address_cityField;
        
        private string primary_address_countryField;
        
        private string primary_address_postalcodeField;
        
        private string primary_address_stateField;
        
        private string primary_address_streetField;
        
        private string rfcField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string dato {
            get {
                return this.datoField;
            }
            set {
                this.datoField = value;
                this.RaisePropertyChanged("dato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string first_name {
            get {
                return this.first_nameField;
            }
            set {
                this.first_nameField = value;
                this.RaisePropertyChanged("first_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id_cliente {
            get {
                return this.id_clienteField;
            }
            set {
                this.id_clienteField = value;
                this.RaisePropertyChanged("id_cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool id_clienteSpecified {
            get {
                return this.id_clienteFieldSpecified;
            }
            set {
                this.id_clienteFieldSpecified = value;
                this.RaisePropertyChanged("id_clienteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                this.last_nameField = value;
                this.RaisePropertyChanged("last_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string primary_address_city {
            get {
                return this.primary_address_cityField;
            }
            set {
                this.primary_address_cityField = value;
                this.RaisePropertyChanged("primary_address_city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string primary_address_country {
            get {
                return this.primary_address_countryField;
            }
            set {
                this.primary_address_countryField = value;
                this.RaisePropertyChanged("primary_address_country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string primary_address_postalcode {
            get {
                return this.primary_address_postalcodeField;
            }
            set {
                this.primary_address_postalcodeField = value;
                this.RaisePropertyChanged("primary_address_postalcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string primary_address_state {
            get {
                return this.primary_address_stateField;
            }
            set {
                this.primary_address_stateField = value;
                this.RaisePropertyChanged("primary_address_state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string primary_address_street {
            get {
                return this.primary_address_streetField;
            }
            set {
                this.primary_address_streetField = value;
                this.RaisePropertyChanged("primary_address_street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string rfc {
            get {
                return this.rfcField;
            }
            set {
                this.rfcField = value;
                this.RaisePropertyChanged("rfc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.tickets.com/")]
    public partial class contactsBeans : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string first_nameField;
        
        private string last_nameField;
        
        private string primary_address_cityField;
        
        private string primary_address_countryField;
        
        private string primary_address_postalcodeField;
        
        private string primary_address_stateField;
        
        private string primary_address_streetField;
        
        private string rfcField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string first_name {
            get {
                return this.first_nameField;
            }
            set {
                this.first_nameField = value;
                this.RaisePropertyChanged("first_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                this.last_nameField = value;
                this.RaisePropertyChanged("last_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string primary_address_city {
            get {
                return this.primary_address_cityField;
            }
            set {
                this.primary_address_cityField = value;
                this.RaisePropertyChanged("primary_address_city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string primary_address_country {
            get {
                return this.primary_address_countryField;
            }
            set {
                this.primary_address_countryField = value;
                this.RaisePropertyChanged("primary_address_country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string primary_address_postalcode {
            get {
                return this.primary_address_postalcodeField;
            }
            set {
                this.primary_address_postalcodeField = value;
                this.RaisePropertyChanged("primary_address_postalcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string primary_address_state {
            get {
                return this.primary_address_stateField;
            }
            set {
                this.primary_address_stateField = value;
                this.RaisePropertyChanged("primary_address_state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string primary_address_street {
            get {
                return this.primary_address_streetField;
            }
            set {
                this.primary_address_streetField = value;
                this.RaisePropertyChanged("primary_address_street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string rfc {
            get {
                return this.rfcField;
            }
            set {
                this.rfcField = value;
                this.RaisePropertyChanged("rfc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Consulta", WrapperNamespace="http://ws.tickets.com/", IsWrapped=true)]
    public partial class ConsultaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tickets.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Skyticket.ContactService.ticketsValidaBeans ticket;
        
        public ConsultaRequest() {
        }
        
        public ConsultaRequest(Skyticket.ContactService.ticketsValidaBeans ticket) {
            this.ticket = ticket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultaResponse", WrapperNamespace="http://ws.tickets.com/", IsWrapped=true)]
    public partial class ConsultaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tickets.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Skyticket.ContactService.contactsBeans[] @return;
        
        public ConsultaResponse() {
        }
        
        public ConsultaResponse(Skyticket.ContactService.contactsBeans[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Actualiza", WrapperNamespace="http://ws.tickets.com/", IsWrapped=true)]
    public partial class ActualizaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tickets.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Skyticket.ContactService.contactsUpBeans cliente;
        
        public ActualizaRequest() {
        }
        
        public ActualizaRequest(Skyticket.ContactService.contactsUpBeans cliente) {
            this.cliente = cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizaResponse", WrapperNamespace="http://ws.tickets.com/", IsWrapped=true)]
    public partial class ActualizaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tickets.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public ActualizaResponse() {
        }
        
        public ActualizaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertaReg", WrapperNamespace="http://ws.tickets.com/", IsWrapped=true)]
    public partial class InsertaRegRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tickets.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Skyticket.ContactService.contactInBeans Inserta;
        
        public InsertaRegRequest() {
        }
        
        public InsertaRegRequest(Skyticket.ContactService.contactInBeans Inserta) {
            this.Inserta = Inserta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertaRegResponse", WrapperNamespace="http://ws.tickets.com/", IsWrapped=true)]
    public partial class InsertaRegResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.tickets.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public InsertaRegResponse() {
        }
        
        public InsertaRegResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ws_ValidaDatos_ClieChannel : Skyticket.ContactService.ws_ValidaDatos_Clie, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ws_ValidaDatos_ClieClient : System.ServiceModel.ClientBase<Skyticket.ContactService.ws_ValidaDatos_Clie>, Skyticket.ContactService.ws_ValidaDatos_Clie {
        
        public ws_ValidaDatos_ClieClient() {
        }
        
        public ws_ValidaDatos_ClieClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ws_ValidaDatos_ClieClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ws_ValidaDatos_ClieClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ws_ValidaDatos_ClieClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Skyticket.ContactService.ConsultaResponse Skyticket.ContactService.ws_ValidaDatos_Clie.Consulta(Skyticket.ContactService.ConsultaRequest request) {
            return base.Channel.Consulta(request);
        }
        
        public Skyticket.ContactService.contactsBeans[] Consulta(Skyticket.ContactService.ticketsValidaBeans ticket) {
            Skyticket.ContactService.ConsultaRequest inValue = new Skyticket.ContactService.ConsultaRequest();
            inValue.ticket = ticket;
            Skyticket.ContactService.ConsultaResponse retVal = ((Skyticket.ContactService.ws_ValidaDatos_Clie)(this)).Consulta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Skyticket.ContactService.ConsultaResponse> Skyticket.ContactService.ws_ValidaDatos_Clie.ConsultaAsync(Skyticket.ContactService.ConsultaRequest request) {
            return base.Channel.ConsultaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Skyticket.ContactService.ConsultaResponse> ConsultaAsync(Skyticket.ContactService.ticketsValidaBeans ticket) {
            Skyticket.ContactService.ConsultaRequest inValue = new Skyticket.ContactService.ConsultaRequest();
            inValue.ticket = ticket;
            return ((Skyticket.ContactService.ws_ValidaDatos_Clie)(this)).ConsultaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Skyticket.ContactService.ActualizaResponse Skyticket.ContactService.ws_ValidaDatos_Clie.Actualiza(Skyticket.ContactService.ActualizaRequest request) {
            return base.Channel.Actualiza(request);
        }
        
        public string Actualiza(Skyticket.ContactService.contactsUpBeans cliente) {
            Skyticket.ContactService.ActualizaRequest inValue = new Skyticket.ContactService.ActualizaRequest();
            inValue.cliente = cliente;
            Skyticket.ContactService.ActualizaResponse retVal = ((Skyticket.ContactService.ws_ValidaDatos_Clie)(this)).Actualiza(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Skyticket.ContactService.ActualizaResponse> Skyticket.ContactService.ws_ValidaDatos_Clie.ActualizaAsync(Skyticket.ContactService.ActualizaRequest request) {
            return base.Channel.ActualizaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Skyticket.ContactService.ActualizaResponse> ActualizaAsync(Skyticket.ContactService.contactsUpBeans cliente) {
            Skyticket.ContactService.ActualizaRequest inValue = new Skyticket.ContactService.ActualizaRequest();
            inValue.cliente = cliente;
            return ((Skyticket.ContactService.ws_ValidaDatos_Clie)(this)).ActualizaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Skyticket.ContactService.InsertaRegResponse Skyticket.ContactService.ws_ValidaDatos_Clie.InsertaReg(Skyticket.ContactService.InsertaRegRequest request) {
            return base.Channel.InsertaReg(request);
        }
        
        public string InsertaReg(Skyticket.ContactService.contactInBeans Inserta) {
            Skyticket.ContactService.InsertaRegRequest inValue = new Skyticket.ContactService.InsertaRegRequest();
            inValue.Inserta = Inserta;
            Skyticket.ContactService.InsertaRegResponse retVal = ((Skyticket.ContactService.ws_ValidaDatos_Clie)(this)).InsertaReg(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Skyticket.ContactService.InsertaRegResponse> Skyticket.ContactService.ws_ValidaDatos_Clie.InsertaRegAsync(Skyticket.ContactService.InsertaRegRequest request) {
            return base.Channel.InsertaRegAsync(request);
        }
        
        public System.Threading.Tasks.Task<Skyticket.ContactService.InsertaRegResponse> InsertaRegAsync(Skyticket.ContactService.contactInBeans Inserta) {
            Skyticket.ContactService.InsertaRegRequest inValue = new Skyticket.ContactService.InsertaRegRequest();
            inValue.Inserta = Inserta;
            return ((Skyticket.ContactService.ws_ValidaDatos_Clie)(this)).InsertaRegAsync(inValue);
        }
    }
}
